spring:
  application:
    name: club-fund-management
  datasource:
    url: jdbc:mysql://localhost:3306/club_fund?createDatabaseIfNotExist=true
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}

app:
  webhook:
    secret: ${WEBHOOK_SECRET}
  bank:
    id: ${BANK_ID}
    account-no: ${BANK_ACCOUNT_NO}
    account-name: ${BANK_ACCOUNT_NAME}
  payos:
    client-id: ${PAYOS_CLIENT_ID}
    api-key: ${PAYOS_API_KEY}
    checksum-key: ${PAYOS_CHECKSUM_KEY}
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000} # 24h
  google:
    client-id: ${GOOGLE_CLIENT_ID}
